export const CANDIDATE_CATALOG_VERSION = '2026-09-22.1';

export interface GeoapifyCandidateCatalogEntry {
  geoapifyCategory: string;
  featureType: string;
  category: string;
  diversityGroup: string;
  score: number;
  osmTags: Record<string, string>;
}

export const GEOAPIFY_CANDIDATE_CATALOG: readonly GeoapifyCandidateCatalogEntry[] = [
  {
    geoapifyCategory: 'man_made.bridge',
    featureType: 'Bridge',
    category: 'bridge',
    diversityGroup: 'bridge',
    score: 95,
    osmTags: { bridge: 'yes' },
  },
  {
    geoapifyCategory: 'religion.place_of_worship',
    featureType: 'Church or place of worship',
    category: 'landmark',
    diversityGroup: 'heritage',
    score: 96,
    osmTags: { amenity: 'place_of_worship' },
  },
  {
    geoapifyCategory: 'building.place_of_worship',
    featureType: 'Church or place of worship',
    category: 'landmark',
    diversityGroup: 'heritage',
    score: 96,
    osmTags: { building: 'church' },
  },
  {
    geoapifyCategory: 'tourism.sights.castle',
    featureType: 'Castle',
    category: 'landmark',
    diversityGroup: 'heritage',
    score: 98,
    osmTags: { historic: 'castle' },
  },
  {
    geoapifyCategory: 'tourism.sights.monastery',
    featureType: 'Monastery',
    category: 'landmark',
    diversityGroup: 'heritage',
    score: 94,
    osmTags: { historic: 'monastery' },
  },
  {
    geoapifyCategory: 'tourism.sights.fort',
    featureType: 'Fort',
    category: 'landmark',
    diversityGroup: 'heritage',
    score: 94,
    osmTags: { historic: 'fort' },
  },
  {
    geoapifyCategory: 'tourism.sights.manor',
    featureType: 'Manor',
    category: 'landmark',
    diversityGroup: 'heritage',
    score: 90,
    osmTags: { historic: 'manor' },
  },
  {
    geoapifyCategory: 'tourism.sights.ruines',
    featureType: 'Ruins',
    category: 'landmark',
    diversityGroup: 'heritage',
    score: 84,
    osmTags: { historic: 'ruins' },
  },
  {
    geoapifyCategory: 'tourism.sights.mine',
    featureType: 'Mine',
    category: 'landmark',
    diversityGroup: 'heritage',
    score: 84,
    osmTags: { man_made: 'mine' },
  },
  {
    geoapifyCategory: 'tourism.sights',
    featureType: 'Landmark',
    category: 'landmark',
    diversityGroup: 'heritage',
    score: 80,
    osmTags: { historic: 'monument' },
  },
  {
    geoapifyCategory: 'memorial.cemetery',
    featureType: 'Cemetery',
    category: 'cemetery',
    diversityGroup: 'memorial',
    score: 93,
    osmTags: { landuse: 'cemetery' },
  },
  {
    geoapifyCategory: 'memorial.graveyard',
    featureType: 'Graveyard',
    category: 'cemetery',
    diversityGroup: 'memorial',
    score: 93,
    osmTags: { landuse: 'cemetery' },
  },
  {
    geoapifyCategory: 'memorial',
    featureType: 'Memorial',
    category: 'landmark',
    diversityGroup: 'memorial',
    score: 80,
    osmTags: { historic: 'monument' },
  },
  {
    geoapifyCategory: 'sport.pitch',
    featureType: 'Sports pitch',
    category: 'sports',
    diversityGroup: 'sport',
    score: 94,
    osmTags: { leisure: 'pitch' },
  },
  {
    geoapifyCategory: 'sport.stadium',
    featureType: 'Stadium',
    category: 'sports',
    diversityGroup: 'sport',
    score: 86,
    osmTags: { leisure: 'sports_centre' },
  },
  {
    geoapifyCategory: 'sport.sports_centre',
    featureType: 'Sports centre',
    category: 'sports',
    diversityGroup: 'sport',
    score: 85,
    osmTags: { leisure: 'sports_centre' },
  },
  {
    geoapifyCategory: 'sport.track',
    featureType: 'Sports track',
    category: 'sports',
    diversityGroup: 'sport',
    score: 82,
    osmTags: { leisure: 'pitch' },
  },
  {
    geoapifyCategory: 'sport.golf_course',
    featureType: 'Golf course',
    category: 'sports',
    diversityGroup: 'sport',
    score: 80,
    osmTags: { leisure: 'pitch' },
  },
  {
    geoapifyCategory: 'man_made.tower',
    featureType: 'Tower',
    category: 'landmark',
    diversityGroup: 'tower',
    score: 90,
    osmTags: { man_made: 'tower' },
  },
  {
    geoapifyCategory: 'man_made.water_tower',
    featureType: 'Water tower',
    category: 'landmark',
    diversityGroup: 'tower',
    score: 89,
    osmTags: { man_made: 'storage_tank' },
  },
  {
    geoapifyCategory: 'man_made.windmill',
    featureType: 'Windmill',
    category: 'landmark',
    diversityGroup: 'tower',
    score: 88,
    osmTags: { man_made: 'windmill' },
  },
  {
    geoapifyCategory: 'man_made.watermill',
    featureType: 'Watermill',
    category: 'landmark',
    diversityGroup: 'tower',
    score: 88,
    osmTags: { man_made: 'watermill' },
  },
  {
    geoapifyCategory: 'man_made.lighthouse',
    featureType: 'Lighthouse',
    category: 'landmark',
    diversityGroup: 'tower',
    score: 90,
    osmTags: { man_made: 'lighthouse' },
  },
  {
    geoapifyCategory: 'man_made.breakwater',
    featureType: 'Breakwater',
    category: 'infrastructure',
    diversityGroup: 'infrastructure',
    score: 82,
    osmTags: { man_made: 'breakwater' },
  },
  {
    geoapifyCategory: 'man_made.pier',
    featureType: 'Pier',
    category: 'infrastructure',
    diversityGroup: 'infrastructure',
    score: 80,
    osmTags: { man_made: 'pier' },
  },
  {
    geoapifyCategory: 'power.substation',
    featureType: 'Power substation',
    category: 'infrastructure',
    diversityGroup: 'power',
    score: 90,
    osmTags: { power: 'substation' },
  },
  {
    geoapifyCategory: 'power.plant',
    featureType: 'Power plant',
    category: 'infrastructure',
    diversityGroup: 'power',
    score: 88,
    osmTags: { power: 'plant' },
  },
  {
    geoapifyCategory: 'power.generator',
    featureType: 'Power generator',
    category: 'infrastructure',
    diversityGroup: 'power',
    score: 86,
    osmTags: { power: 'generator' },
  },
  {
    geoapifyCategory: 'production.factory',
    featureType: 'Factory',
    category: 'industrial',
    diversityGroup: 'industry',
    score: 78,
    osmTags: { landuse: 'industrial' },
  },
  {
    geoapifyCategory: 'production.brewery',
    featureType: 'Brewery',
    category: 'industrial',
    diversityGroup: 'industry',
    score: 76,
    osmTags: { landuse: 'industrial' },
  },
  {
    geoapifyCategory: 'production.pottery',
    featureType: 'Pottery works',
    category: 'industrial',
    diversityGroup: 'industry',
    score: 76,
    osmTags: { landuse: 'industrial' },
  },
  {
    geoapifyCategory: 'production.winery',
    featureType: 'Winery',
    category: 'industrial',
    diversityGroup: 'industry',
    score: 76,
    osmTags: { landuse: 'industrial' },
  },
  {
    geoapifyCategory: 'education.school',
    featureType: 'School',
    category: 'public-building',
    diversityGroup: 'civic',
    score: 88,
    osmTags: { amenity: 'school' },
  },
  {
    geoapifyCategory: 'building.school',
    featureType: 'School',
    category: 'public-building',
    diversityGroup: 'civic',
    score: 88,
    osmTags: { building: 'school' },
  },
  {
    geoapifyCategory: 'healthcare.hospital',
    featureType: 'Hospital',
    category: 'public-building',
    diversityGroup: 'civic',
    score: 84,
    osmTags: { amenity: 'hospital' },
  },
  {
    geoapifyCategory: 'entertainment.museum',
    featureType: 'Museum',
    category: 'landmark',
    diversityGroup: 'civic',
    score: 84,
    osmTags: { tourism: 'museum' },
  },
  {
    geoapifyCategory: 'activity.community_center',
    featureType: 'Community centre',
    category: 'public-building',
    diversityGroup: 'civic',
    score: 78,
    osmTags: { amenity: 'community_centre' },
  },
  {
    geoapifyCategory: 'building.public_and_civil',
    featureType: 'Public building',
    category: 'public-building',
    diversityGroup: 'civic',
    score: 78,
    osmTags: { building: 'public' },
  },
  {
    geoapifyCategory: 'building.transportation',
    featureType: 'Transport building',
    category: 'building',
    diversityGroup: 'civic',
    score: 76,
    osmTags: { building: 'public' },
  },
  {
    geoapifyCategory: 'building.industrial',
    featureType: 'Industrial building',
    category: 'industrial',
    diversityGroup: 'industry',
    score: 78,
    osmTags: { building: 'industrial' },
  },
  {
    geoapifyCategory: 'airport.airfield',
    featureType: 'Airfield',
    category: 'aviation',
    diversityGroup: 'aviation',
    score: 94,
    osmTags: { aeroway: 'aerodrome' },
  },
  {
    geoapifyCategory: 'airport.gliding',
    featureType: 'Gliding airfield',
    category: 'aviation',
    diversityGroup: 'aviation',
    score: 94,
    osmTags: { aeroway: 'aerodrome' },
  },
  {
    geoapifyCategory: 'populated_place.village',
    featureType: 'Village centre',
    category: 'settlement',
    diversityGroup: 'settlement',
    score: 72,
    osmTags: { place: 'village' },
  },
  {
    geoapifyCategory: 'populated_place.hamlet',
    featureType: 'Hamlet centre',
    category: 'settlement',
    diversityGroup: 'settlement',
    score: 68,
    osmTags: { place: 'hamlet' },
  },
  {
    geoapifyCategory: 'populated_place.town',
    featureType: 'Town centre',
    category: 'settlement',
    diversityGroup: 'settlement',
    score: 70,
    osmTags: { place: 'town' },
  },
  {
    geoapifyCategory: 'populated_place.city',
    featureType: 'City centre',
    category: 'settlement',
    diversityGroup: 'settlement',
    score: 70,
    osmTags: { place: 'city' },
  },
  {
    geoapifyCategory: 'natural.forest',
    featureType: 'Forest',
    category: 'terrain',
    diversityGroup: 'terrain',
    score: 70,
    osmTags: { natural: 'forest' },
  },
  {
    geoapifyCategory: 'natural.water',
    featureType: 'Lake or pond',
    category: 'water',
    diversityGroup: 'water',
    score: 86,
    osmTags: { natural: 'water' },
  },
  {
    geoapifyCategory: 'waterway',
    featureType: 'Waterway',
    category: 'water',
    diversityGroup: 'water',
    score: 82,
    osmTags: { waterway: 'river' },
  },
];

export const GEOAPIFY_SEARCH_CATEGORIES = GEOAPIFY_CANDIDATE_CATALOG.map(
  ({ geoapifyCategory }) => geoapifyCategory
).join(',');

export function catalogEntryForGeoapifyCategories(
  categories: readonly string[]
): GeoapifyCandidateCatalogEntry | null {
  return (
    GEOAPIFY_CANDIDATE_CATALOG.find(({ geoapifyCategory }) =>
      categories.some(
        (category) => category === geoapifyCategory || category.startsWith(`${geoapifyCategory}.`)
      )
    ) ?? null
  );
}
